### PR TITLE
fixing documents

### PR DESCRIPTION
**Pull request by c-chaitanya**
- [ ✓] I've [seen the `doc/README.md` file](https://github.com/plotly/plotly.py/blob/master/doc/README.md)

While going through the documentation on https://plotly.com/python/colorscales/ I realised that this parameter ```color_continous_midpoint``` does not exist. This was a typo for ```color_continuous_midpoint```.  
While fixing this I noticed a few other misspelt words. So I made a little NLP project for myself and wrote a script which would print all misspelt words to a file. I then went through the spellings and  corrected them manually.

### CODE REVIEW

**Comment by c-chaitanya** [comment]
Hi @nicolaskruchten , this pull request is nothing but a mega branch of spelling correction and a few typo fixes in parameter names. All changes are included only in the documentation part. Yet two tests in circleci seem to fail. Am I missing some step somewhere. Is it something I can fix?

**Comment by nicolaskruchten** [comment]
Thanks very much for these fixes! I'll retarget your PR to the `doc-prod` branch and merge now.

**Comment by nicolaskruchten** [comment]
Hmm, actually I can't grab just your commit into `doc-prod` right now, as it's based on `master` which has unreleased changes. If you could cherry-pick this commit onto `doc-prod` and submit a new PR I would merge it immediately :)

**Comment by c-chaitanya** [comment]
Hi thanks for the response @nicolaskruchten. Here is the new pull request https://github.com/plotly/plotly.py/pull/3073

**Pull request closed without merging**
