### PR TITLE
Support calling orca through xvfb on Linux

### PR DESCRIPTION
**Pull request by jonmmease**
## Overview
This PR adds support for calling orca through Xvfb, simplifying the process of using plotly.py's image export functions in a headless Linux environment.

This is accomplished through the addition of a new `use_xvfb` parameter in `plotly.io.orca.config`.  This parameter may be set to `False`, `True`, or `'auto'`, where:
  - `False`: Never use xvfb
  - `True`: Use Xvfb and raise an error if `xvfb-run` is not found on the system Path
  - `'auto'`:  Use Xvfb if running on Linux, no display serer is detected (determined by checking the `DISPLAY` environment variable), and `xvfb-run` is on the path.

`use_xvfb` will default to `False` for the remainder of version 3, but it will default to `'auto'` in version 4.  The new `orca_defaults` future flag may be used to enable this default behavior now.

## Additional Changes 
Add `LD_PRELOAD` to the list of environment variables to be excluded to be unset when calling orca to avoid breaking orca in Colab (See https://medium.com/@n0mad/how-i-trained-starcraft-2-ais-using-googles-free-gpus-44bc635b0418 for discussion of the Colab's use of tcmalloc).

### CODE REVIEW

**Comment by jonmmease** [comment]
Using plotly.py with orca in Colab
```
!pip install https://11956-14579099-gh.circle-artifacts.com/0/dist/plotly-3.8.0%2B2.g4a2ccc2e.tar.gz
!apt-get install xvfb libgtk2.0-0 libgconf-2-4

!wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local
!conda install -q -y --prefix /usr/local -c plotly plotly-orca

import sys
sys.path.append('/usr/local/lib/python3.6/site-packages/')
sys.path.append('/usr/local/bin')
```

```python
from _plotly_future_ import v4
import plotly.io as pio
import plotly.graph_objs as go

fig = go.Figure(data=[{'y': [3, 2, 4]}])
pio.to_image(fig)
```

**Comment by jonmmease** [comment]
orca setup for use in Kaggle kernels

```
!pip install https://11970-14579099-gh.circle-artifacts.com/0/dist/plotly-3.8.0%2B3.g27437f41.tar.gz
!conda install -y -c plotly plotly-orca
!apt-get -y install libxss1
```

If the Kaggle Python docker image (https://github.com/Kaggle/docker-python/blob/master/Dockerfile) was updated to include `conda install -y -c plotly plotly-orca` and `apt-get -y install libxss1` then orca would work out-of-the-box with the changes in this branch since Xvfb is already included.

**Comment by jonmmease** [comment]
Unfortunately, it appears this approach won't work with Azure notebooks because sudo is required to use `apt-get` to install Xvfb and sudo isn't supported right now https://github.com/Microsoft/AzureNotebooks/issues/303.

**Comment by atan4583** [comment]
Hello, 

I installed orca using `conda install -c plotly plotly-orca` on Amazon Linux server, then got this error when calling plotly:
`/opt/conda/envs/pysig/lib/orca_app/orca: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory`
  
I read that I need to install Xvfb on the Amazon Linux server, but all the instructions I can find for installation Xvfb only mention ubuntu server involving orca-X.Y.Z-x86_64.AppImage. As my linux server is Amazon linux, so I installed Xvfb using `sudo yum install Xvfb`. This installed Xvfb installed in **/usr/bin/** but there is no orca-X.Y.Z-x86_64.AppImage to be found anywhere. 

Further more, when I tried to start Xvfb using `/usr/bin/Xvfb :1 -screen 0 1152x900x8&`, I got the error `_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created`. 

Could someone direct me how to get Xvfb on Amazon Liunx server `started` and how to make it work with orca please? 

Thank you in advance.

**Pull request merged**
