### PR TITLE
Choldgraf custom colors trisurf

### PR DESCRIPTION
**Pull request by Kully**
@choldgraf @theengineear 

Added the 'it' to that error message. Everything worked on my end and it looks good.

Plus, I made some modern art with `import random`:

modern art

### CODE REVIEW

**Comment by theengineear** [comment]
Great! 💃

**Comment by choldgraf** [comment]
hah that's awesome. (so I shouldn't worry about my PR anymore, right?)

**Comment by theengineear** [comment]
Yah @choldgraf to speed things up, we're just knabbing your commits and throwing them into a `plotly/plotly.py` repo branch to iterate a bit more collaboratively here as necessary.

Note that you *can* still add updates to your branch as necessary and we can either rebase or merge them into the new branch we've created to include them.

We're just avoiding having weird code state in our `master` branch as much as possible.

**Comment by choldgraf** [comment]
no problem, if you guys are happy w/ this codebase then I say go for it. I'll push a little repo to do brain plotting, and we can see how the performance holds up. I got it down to ~4-6 seconds on the python side on my browser, and probably another 4-5 seconds for the browser to actually render the scene and plot. The biggest challenge I came across was that it looks like something isn't getting garbage collected on the JS side, because after a few plots the browser becomes really slow and uses up a ton of memory. But that's probably for a different PR.

**Comment by cldougl** [comment]
@Kully (cc @choldgraf ) I'm updating our pip version now, could you update the [changelog](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#change-log) when you have a minute (your changes will be applied to [v1.11.0](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#1110---2016-05-27)) :)

**Pull request merged**
