### PR TITLE
Fix for #1809 Python 2.7 incompatibility in the iframe renderer

### LINKED ISSUE #1809: Python 2.7 incompatibility in the iframe renderer
Plotly with python 2.7 fails when using the `iframe` renderer, due to a Python 3 call to os.makedirs with the exist_ok flag.

Minimum failing example:
`import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3])],
    layout_title_text="A Figure Displayed with the 'png' Renderer"
)
fig.show(renderer="iframe")`

### PR DESCRIPTION
**Pull request by carthurs**
Fixes #1809

### CODE REVIEW

**Comment by jonmmease** [comment]
Thanks for catching this and for the fix @carthurs!  One comment is that I just looked up the [CPython 3 implementation](https://github.com/python/cpython/blob/734f1202a50641eb2c4bfbcd5b75247c1dc99a8f/Lib/os.py#L220-L226), and it includes a comment that the `EEXIST` error code isn't necessarily reliable for detecting that `mkdir` failed  due to the existence of a directory.

```python
    try:
        mkdir(name, mode)
    except OSError:
        # Cannot rely on checking for EEXIST, since the operating system
        # could give priority to other errors like EACCES or EROFS
        if not exist_ok or not path.isdir(name):
            raise
```

Unless you have thoughts otherwise, I'd rather mimic this implementation to be on the safe side.

**Comment by carthurs** [comment]
Do we really care why it failed, if it failed for a reason other than the dir existing? I feel it'd be better to explicitly list the errors that are acceptable in the guard, rather than CPython's approach of blanket-accepting all errors.

(CPython's implementation is going to swallow _any and all_ errors from mkdir in the case where `exist_ok = True` and the path exists already.)

With regards to this:
```python
        # Cannot rely on checking for EEXIST, since the operating system
        # could give priority to other errors like EACCES or EROFS
```
If the OS is (in addition to `EEXIST`, but with priority) raising `EACCES` (permission denied) or `EROFS` (read-only file system) - or any other error really -  then I don't see the problem with having that case pass the guard and the exception being re-raised.

Besides, I think mimicking CPython would probably involve writing the recursive function again ourselves - or using `pathlib`, plus the `pathlib2` backport to manage this.

Here's my existing solution, for reference.
```python
        try:
            os.makedirs(filedir)
        except OSError as error:
            if error.errno != errno.EEXIST:
                raise
```

**Comment by casperdcl** [comment]
nice https://github.com/python/cpython/commit/a82642f9dbdff5253f40d4acee0cbb27aaf34462 it could be the case that e.g. `EACCES` is raised even if `EACCES` isn't the real problem.

I'd say it's an upstream bug @carthurs but we should probably just use the CPython hack.

**Comment by carthurs** [comment]
@casperdcl looks like it is due to how Windows functions in an edge-case https://bugs.python.org/issue25583 

The original solution proposed on there was
```python
if not (exist_ok and path.isdir(name) and
            e.errno in (errno.EEXIST, errno.EACCES)):
```

But then this was rejected because "mkdirs shouldn't use e.errno at all. Because, as said in docstring, makedirs must first check whether a folder exists, and only then call mkdir."

So I think the fix of checking EACCES and EEXIST here should do the job.

**Comment by jonmmease** [comment]
I would be more comfortable with the following:
```python
        try:
            os.makedirs(filedir)
        except OSError as error:
            if not path.isdir(name):
                raise
```
I think this captures the intent of "only raise if we don't end up with the directory existing", without including logic for handling platform differences.  I'd rather not need to worry about which error code is raised on, for example, Windows 10 running on a raspberry pi :slightly_smiling_face:

**Comment by jonmmease** [comment]
We're going to release 4.2.0 shortly, so I'll go ahead and merge this and then follow up with a small PR updating the `except` block as I described above.  Thanks again for the report and contribution @carthurs!

**Comment by carthurs** [comment]
@jonmmease Glad to be of help here! I agree that your suggestion,
>```python
>try:
>            os.makedirs(filedir)
>        except OSError as error:
>            if not path.isdir(name):
>                raise
>```
- explicitly defining what is acceptable for all possible cases - is exactly the right solution in the end. Thanks for the discussion!

**Pull request merged**
