### PR TITLE
Starting AI/ML section in python docs [3rd attempt]

### PR DESCRIPTION
**Pull request by xhlulu**
1st attempt: https://github.com/plotly/plotly.py/pull/2172
2nd attempt: https://github.com/plotly/plotly.py/pull/2276
Original Issue: https://github.com/plotly/plotly.py/issues/2153

Had to make a new PR since I messed up the branch with unresolved conflicts after rebasing on `doc-prod`. This one should be fine (hopefully).

Changes:
- Added scikit-learn to requirements

Todo list:
- [x] Create a ML section
- [x] kNN Classification notebook
- [x] Regression notebook
- [x] ROC notebook
- [x] PCA notebook
- [ ] tSNE/UMAP notebook
- [ ] LIME (follow [this example](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20images.html))

### CODE REVIEW

**Comment by xhlulu** [comment]
@nicolaskruchten I am unable to add the `umap-learn` library to the `doc/requirements.txt`. Can you do that?

**Comment by nicolaskruchten** [comment]
Unable how?

**Comment by xhlulu** [comment]
I'm not sure. I can't push when it is added.

**Comment by xhlulu** [comment]
I'll try again tomorrow

**Comment by xhlulu** [comment]
@nicolaskruchten Seems like it worked now. Not sure what happened, but it's ready to review now.

**Comment by nicolaskruchten** [comment]
OK, this looks really good, thanks for the updates! I went through and fixed a bunch of random little things. Let's see what the CI run looks like in a few minutes and I can try to fix it up and merge this stuff.

**Comment by nicolaskruchten** [comment]
OK this is pretty great, merging!

**Pull request merged**
