### PR TITLE
updated subplots import in figure factories

### PR DESCRIPTION
**Pull request by emmanuelle**

### CODE REVIEW

**Comment by emmanuelle** [comment]
This issue was noticed in https://community.plot.ly/t/custom-scatterplot-matrix-splom/31243/6

**Comment by nicolaskruchten** [comment]
Are the functions which this touches under test or...? Is this a bugfix or just cosmetic? I'm OK either way, just curious :)

**Comment by emmanuelle** [comment]
It's only cosmetic, the current code is under test and works.

**Comment by nicolaskruchten** [comment]
💃

**Pull request merged**
