### PR TITLE
py2.6 support

### PR DESCRIPTION
**Pull request by casperdcl**
basic support for an old server running python2.6

### CODE REVIEW

**Comment by theengineear** [comment]
I'm going to close this for now, but feel free to reopen if we decide to revert our previous decision to stop testing on Python 2.6

**Comment by casperdcl** [comment]
Hi @theengineear. I sympathise with not actively supporting py2.6. However a PR which introduces backward compatibility without breaking anything (and which passes all unit tests) seems to merit merging. Many hosts still only support py2.6 and it's a little silly to keep rebasing my patched fork version onto future changes here.

Check out this hit counter link from one of my repos to see plotly.py2.6 in action: [tqdm-hits](http://caspersci.uk.to/cgi-bin/hits.cgi?q=tqdm&a=plot&r=https:%2F%2Fgithub.com%2Ftqdm%2Ftqdm)

**Comment by theengineear** [comment]
@casperdcl point definitely taken. Did you manage to find *all* the cases where we use `{}` instead of `{0}`, etc for formatting? 

http://stackoverflow.com/questions/19668395/str-format-for-python-2-6-gives-error-where-2-7-does-not

I remember that being a pain.

If you're sure those are all taken care of, I could be swayed. We should make sure to officially add it back as a tested version in our CI tests though.

**Comment by theengineear** [comment]
>We should make sure to officially add it back as a tested version in our CI tests though.

And I'll handle doing this portion since we do some funny things in our CI setup.

**Comment by casperdcl** [comment]
I only fixed what was necessary to get this basic plot working. I could grep through the rest if you'd like.

**Comment by theengineear** [comment]
//cc @chriddyp , as much as I always want to move to Python 3, perhaps I've been a little over-zealous. I'm down to add back Python 2.6 if it's as painless as @casperdcl says ;)

I can work on adding some commits to this PR that add back testing for Python 2.6.

**Comment by chriddyp** [comment]
Sure, if it's not too much of a problem going forward then I'm OK with it.

**Comment by jonmmease** [comment]
Closing as this PR is pretty stale and at this point we're not interested in supporting Python 2.6. Thanks!

**Comment by casperdcl** [comment]
No worries. It's getting harder to support py2.6 every day.

**Pull request closed without merging**
