### PR TITLE
webgl in scatterplotmatrix

### PR DESCRIPTION
**Pull request by Kully**

### CODE REVIEW

**Comment by Kully** [comment]
@theengineear ready for review

**Comment by Kully** [comment]
Will merge with master once https://github.com/plotly/plotly.py/pull/652 is merged.

**Comment by etpinard** [comment]
That's a horrible idea. gl2d subplots are _sloooooooooow_. Even though individual gl2d subplots can display far more points than their svg counterpart, graphs with 4+ gl2d subplots are incredibly slow to render at the moment.

**Comment by Kully** [comment]
> That's a horrible idea. gl2d subplots are sloooooooooow. Even though individual gl2d subplots can display far more points than their svg counterpart, graphs with 4+ gl2d subplots are incredibly slow to render at the moment.

Okay, so I wasn't crazy when I was seeing avg run times that were greater in webgl vs non webgl subplots.

I was only doing this for a user who asked for this feature to speed up their scatterplotmatrices. I suppose I'll just let them know all this

**Comment by etpinard** [comment]
@Kully Probably a good idea to point plotly.py gl2d users to https://github.com/plotly/plotly.js/issues/130 for more info on the current limitations.

**Comment by theengineear** [comment]
>That's a horrible idea.

😆

Cool, I have no problem adding this in now. It's just an minor inconvenience wrt conflicts, that's all.

**Comment by theengineear** [comment]
Disregard that deleted comment, I read @etpinard's comment too fast. Sweet, thanks chiming in on this one.

**Comment by Kully** [comment]
> Cool, I have no problem adding this in now. It's just an minor inconvenience wrt conflicts, that's all.

If it's slower tho, i should abandon the PR no?

**Pull request closed without merging**
