### PR TITLE
Replaced 'retrying' dependency with 'tenacity' in plotly package

### PR DESCRIPTION
**Pull request by jmsmdy**
The plotly dependency 'retrying' is no longer being maintained. The currently-maintained fork, 'tenacity', is compatible with both Python 2 and 3, and is feature-compatible (although not API compatible). This pull request changes the few instances where the retrying package is used in plotly to use tenacity instead. 

One motivation for this is to get plotly working in Pyodide (a means developed by Firefox to run Python in the browser, which currently supports numpy, pandas, matplotlib, and a number of other datascience packages). 'Retrying' seems to be incompatible with Pyodide.

closes https://github.com/plotly/plotly.py/issues/2907

### CODE REVIEW

**Comment by jmsmdy** [comment]
It looks like the orca tests are failing with "ModuleNotFoundError: No module named 'tenacity'". I assume this is only because tenacity is not available on the CI server. Not sure what to do about this!

**Comment by Alex-Monahan** [comment]
This change made our use case possible! If it could be merged at some point (no urgency!), that would be fantastic. 

Thanks!
-Alex

**Comment by nicolaskruchten** [comment]
Thanks @jmsmdy! Pyodide is so cool, I'm glad someone is excited about getting Plotly working there <3 

@jonmmease this seems like a reasonable PR to merge once we get CI running green, right?

**Comment by jonmmease** [comment]
Thanks @jmsmdy. Glad to learn that `retrying` lives on in `tenacity`.

Looks like tenacity is available on PyPI, the anaconda main channel, and conda-forge so I wouldn't consider this to be a breaking change.  Happy to see this merged when tests are worked out, looks like we need to track down the dependencies used in the orca CI tests and add tenacity there as well.

**Comment by nicolaskruchten** [comment]
OK, let's get this thing merged then! @jmsmdy can you please allow me to push to your branch? If not, can you please run `black` on `_orca.py` and replace `retrying` with `tenacity` in `create_conda_optional_env.sh` and push?

**Comment by jmsmdy** [comment]
> OK, let's get this thing merged then! @jmsmdy can you please allow me to push to your branch? If not, can you please run `black` on `_orca.py` and replace `retrying` with `tenacity` in `create_conda_optional_env.sh` and push?

Just invited you as a collaborator on my branch, feel free to make whatever changes are necessary!

**Comment by jmsmdy** [comment]
@nicolaskruchten I made the changes you suggested, but now the docs don't seem to be building (none of the commits I made changed the docs). Looking at the CircleCI output for build-doc, the error for an example doc build (which is the same as the error for many docs which failed), is as follows:

`[NbConvertApp] Converting notebook build/ipynb/plotly-express.ipynb to html
[NbConvertApp] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/home/circleci/project/doc/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 384, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/circleci/project/doc/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/circleci/project/doc/nb.tpl", line 1, in top-level template code
    {%- extends 'basic.tpl' -%}
jinja2.exceptions.TemplateNotFound: basic.tpl`

Searching through the plotly.py repository, I can't seem to find the file basic.tpl anywhere. Could you provide some guidance for how to fix this?

**Comment by nicolaskruchten** [comment]
> I can't seem to find the file basic.tpl anywhere. Could you provide some guidance for how to fix this?

Don't worry about the doc CI failures, I think it's just that we need to pin `nbconvert` to 5.x on master.

**Comment by nicolaskruchten** [comment]
Re the `chart-studio` package, I would indeed recommend not changing anything in there at all if possible :)

**Comment by jmsmdy** [comment]
OK, so after rolling back changes to chart-studio, and adding some jinja template files from nbconvert to the docs folder, all tests are passing. Should I add a new commit removing the jinja template files I added to get the docs test to pass?

**Comment by nicolaskruchten** [comment]
Hmm let me take a look at those templates! Thanks for pushing through that failure!

**Comment by jmsmdy** [comment]
The templates were obtained from the 5.6.1 version of nbconvert, here: https://github.com/jupyter/nbconvert/tree/5d2eaed5cbba1f8dff14126c015f4fe28f5f3311/nbconvert/templates 

I just searched for basic.tpl, then traced back the template imports. The templates I added are are `doc/basic.tpl`, `doc/display_priority.tpl`, and `doc/null.tpl`.

**Comment by nicolaskruchten** [comment]
OK so on `master` I've pinned `nbconvert` down to the version that has `basic.tpl` built-in, so in principle you should be able to remove these templates and rebase onto master (or merge master in) and things should still be green.

**Comment by jmsmdy** [comment]
OK, just rebased to master and removed the (now unneeded) jinja templates that I previously added. As far as I can tell, this is ready to marge!

**Comment by nicolaskruchten** [comment]
This looks good to merge to me! @jonmmease any objections?

@jmsmdy thanks so much for this, I'll likely merge it right before the next minor release (i.e. 4.15) early in the new year.

**Comment by rth** [comment]
> I'll likely merge it right before the next minor release (i.e. 4.15) early in the new year.

Any remaining blockers for merging this PR ? Thanks!

**Comment by nicolaskruchten** [comment]
No blockers, but the next version of Plotly.py will be 5.0, in a few weeks' time :)

**Comment by jonmmease** [comment]
Thanks!

**Pull request merged**
