### PR TITLE
Use uuid4 instead of uuid1 to generate trace uid

### PR DESCRIPTION
**Pull request by erichiggins**
This PR addresses #1235 .
I didn't see any existing tests which specifically test this functionality. Since this issue and fix has more to do with core Python, I'm not entirely convinced that they would be that useful.

### CODE REVIEW

**Comment by jonmmease** [comment]
Thanks for the PR @erichiggins! Our CI tests aren't running right now due to some issues with GitHub, but once they come back up I'll pull this in.

**Comment by erichiggins** [comment]
It's not clear from the tracebacks in the CI tests failed due to my change or something else. It doesn't _appear_ to be related at first glance.  Looks like other PRs are failing on them as well.

**Comment by jonmmease** [comment]
Hi @erichiggins , I think the tests are fixed on master now (but we're still experiencing some issues since the GitHub problems yesterday).  Please merge master and push when you have a chance.

**Comment by erichiggins** [comment]
@jonmmease Done! Looks like that fixed it.

Syncing and merging forks is a bit outside my usual workflow, so the merge/rebase could probably have been cleaner. Sorry if it introduces any noise into the commit history.

**Comment by jonmmease** [comment]
Thanks @erichiggins , I'm not quite sure why this PR is showing "368 Files Changed" with respect to master. I think GitHub may be a bit behind.  In any case I'll take it from here 🙂

**Pull request merged**
