### PR TITLE
PX internals renaming

### PR DESCRIPTION
**Pull request by nicolaskruchten**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
@emmanuelle this one is probably good to review commit by commit

**Comment by emmanuelle** [comment]
The renaming looks good to me, thanks it's clearly an improvement for devs. I don't understand the build-doc CI failure though. I was looking for the log files but could not find them in the artifacts??

**Comment by nicolaskruchten** [comment]
Ah we updated one of the CI checks, so I need to rebase.

**Comment by emmanuelle** [comment]
:dancer:

**Pull request merged**
