### PR TITLE
Support for embedding plotlywidget instances that use numpy arrays

### PR DESCRIPTION
**Pull request by jonmmease**
See https://github.com/plotly/plotly.py/issues/1116 for background.

With these updates it is now possible to embed `FigureWidget` instances containing numpy arrays in static contexts (e.g. nbviewer, and soon Plotly Cloud).

I also took to opportunity to update the auto-resizing logic to:
  - Support the classic notebook
  - Still resize width even if the height is set explicitly (See https://github.com/plotly/plotly.py/issues/1041#issuecomment-411297737)

This change involves no changes to the Python library, so we should be able to release this as `plotlywidget@0.2.2` without making a release of plotly.py yet.

Also, to help with embedding, this version emits an event named `'plotlywidget-after-render'` when the widget rendering process is complete.

cc @tarzzz

### CODE REVIEW

**Comment by jonmmease** [comment]
@tarzzz , if I publish this branch as `plotlywidget@0.2.2-rc.1` will you be able to test with this version?  
Being an rc, you won't get it without specifying the version explicitly, and I'm not sure if you're able to do that.

**Comment by tarzzz** [comment]
@jonmmease I tested  `0.2.2-rc.2` with Plotly Cloud and everything looks good.. !!

**Comment by jonmmease** [comment]
Merged in the CircleCI 2.0 integration

**Comment by jonmmease** [comment]
@tarzzz Great! I'm going to merge this.  My plan is to release this along with plotly.py version 3.2.0 and `plotlywidget` 0.3 (which will include Plotly.js 1.40).  But let me know if you have particular time constraints you're working with.

**Pull request merged**
