### PR TITLE
start orca with --no-sandbox flag

### PR DESCRIPTION
**Pull request by emmanuelle**
fix proposed by @antoinerg

### CODE REVIEW

**Comment by antoinerg** [comment]
Little update: running `circleci-cli local execute --job python-3-5-orca` from this branch now passes. However, it still doesn't pass on CircleCI somehow :confused:

**Comment by nicolaskruchten** [comment]
@antoinerg is this stalled for now?

**Comment by antoinerg** [comment]
@nicolaskruchten I am hoping to have it fixed within the next hour. I'll update you very soon.

**Comment by antoinerg** [comment]
Closing in favor of #2307

**Pull request closed without merging**
