### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joydisette**
jupyter build times-out. Updated steps from this thread https://discourse.jupyter.org/t/installing-extensions-extremely-slow/2627

### CODE REVIEW

**Comment by emmanuelle** [comment]
Thank you for your pull request @joydisette ! It's also very interesting for us to read the discussion on the jupyter discourse so thanks for sharing the link. Did this time-out happen to you? If this problem has happened many times I'll be in favor of adding this tip, but I'll let @nicolaskruchten or @jonmmease  comment first since they know more than me about the plotly bundles.

**Comment by emmanuelle** [comment]
the CI failure has nothing to do with you so don't worry about this

**Comment by joydisette** [comment]
@emmanuelle yes it did time-out for me too

**Comment by emmanuelle** [comment]
Thank you @joydisette ! So we're trying to have quite a lot of stuff about Jupyterlab in the `README.md` (since several things can go wrong :-(), so probably I will refactor the README to move some instructions and your addition to the troubleshooting guide https://plot.ly/python/troubleshooting/. I'll make sure to pick your commit so that you are duly credited. Thanks again :-).

**Comment by nicolaskruchten** [comment]
I'm not sure we want to recommend that people use dev builds, actually, as it could have unintended consequences for other extensions. I hope that this kind of thing will become unnecessary once #2441 is done.

**Pull request closed without merging**
