### PR TITLE
debug

### PR DESCRIPTION
**Pull request by emmanuelle**
to test the new js build

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
FYI it's not necessary to make a PR or any commits to get a new dev build from the Plotly.js master... You can go into CircleCI under the master branch i.e. https://circleci.com/gh/plotly/plotly.py/tree/master and find the latest `dev_build` build and hit "rerun"

image

**Comment by nicolaskruchten** [comment]
FWIW the build containing the rangebreaks and unified-hover stuff is here now:

`pip install https://33619-14579099-gh.circle-artifacts.com/0/packages/python/plotly/dist/plotly-4.5.4%2B27.g1c232fd4f.tar.gz` but it'll surely be out of date in a day or so as we squash some bugs :)

**Comment by nicolaskruchten** [comment]
Ah also, given how sensitive the JupyterLab installation is, please note that you can only test this kind of build in Classic Notebooks I think.

**Comment by emmanuelle** [comment]
ok, thanks for the tips for using the JS master, I had forgotten about this possibility. Did you see the percy changes? I'm a bit puzzled about where they come from.

**Pull request closed without merging**
