### PR TITLE
sync chunked requests proxy updates

### PR DESCRIPTION
**Pull request by BRONSOLO**
ping @theengineear or @chriddyp

### CODE REVIEW

**Comment by theengineear** [comment]
@BRONSOLO we error if the default schema is out of date:

>Run `make update_default_schema` to fix it!

^^ as the error output says :) mind committing the change from that and updating this PR?

**Comment by theengineear** [comment]
:dancer: after :memo:s

**Comment by BRONSOLO** [comment]
@theengineear running the command doesn't make a diff. suggestions : ) I'll debug.

**Comment by BRONSOLO** [comment]
thanks @theengineear!

**Pull request merged**
