### PR TITLE
add rugplot + changelog

### PR DESCRIPTION
**Pull request by Kully**
Fixes this issue: https://github.com/plotly/plotly.py/issues/603

### CODE REVIEW

**Comment by Kully** [comment]
@theengineear ready for a quick 👀

**Comment by theengineear** [comment]
Huh, weird intermittent sign-in failure... If it keeps happing, you could mock the `users.current` request so that it just skips the validation part. Up to you. My guess is that a rebuild will work for now though.

**Comment by Kully** [comment]
> Huh, weird intermittent sign-in failure... If it keeps happing, you could mock the users.current request so that it just skips the validation part. Up to you. My guess is that a rebuild will work for now though.

I tried rebuilding once and the same error occurred

**Comment by theengineear** [comment]
LGTM, *but*, is there an existing test that you can improve to cover this? The `violin` coverage is only at 62%, which isn't great. https://1894-14579099-gh.circle-artifacts.com/0/tmp/circle-artifacts.mLgBx3K/coverage-reports/py27-optional/plotly_figure_factory__violin_py.html

💃 as is, but it'd be great to add some test coverage 😸

**Comment by theengineear** [comment]
>I tried rebuilding once and the same error occurred

Did it occur for the same Python version in the same test? I ask because it's a little odd.

**Comment by Kully** [comment]
> Did it occur for the same Python version in the same test? I ask because it's a little odd.

It looks like one was Python 3.4.3 and the other Python 3.3.3.

**Comment by Kully** [comment]
> 💃 as is, but it'd be great to add some test coverage 😸

I didn't know about this test coverage page, sooo cool! Sure, I'll some before merging then ping you.

**Comment by theengineear** [comment]
>I didn't know about this test coverage page

ya! definitely good to check in with every now and again!

**Comment by Kully** [comment]
And scatterplotmatrix is at 41% - ouch!

I think a lot of the coverage is coming from not checking all types of violins or scatterplot matrices.

**Comment by Kully** [comment]
Change of plans, I'm just going to merge this guy.

I don't really understand how the coverage page works...it says https://1894-14579099-gh.circle-artifacts.com/0/tmp/circle-artifacts.mLgBx3K/coverage-reports/py27-optional/plotly_figure_factory__violin_py.html#n556 is not covered for instance, even though there _is_ a test for it. And if I decided to test `violin_colorscale` then I don't know if it would increase the coverage %.

Can you illuminate how this works?

**Comment by theengineear** [comment]
@Kully the link you pasted suggests that the following condition is not met:

`if pd and isinstance(data, pd.core.frame.DataFrame):`

Therefore, none of the code inside that is ever touched. That means that either `pd` is not imported or `data` is not an instance of `pd.core.frame.DataFrame`.

**Pull request merged**
