### PR TITLE
substituted deprecated numpy types and matplotlib arguments

### PR DESCRIPTION
**Pull request by eisenlohr**
Replaced deprecated numpy.dtypes

  * `np.bool` ==> `bool`
  *  `np.int` ==> `int`
  *  `np.float` ==> `float`

Replaced deprecated Matplotlib bar arguments

  * `left` ==> `x`
  *  `bottom` ==> `y`

## Code PR

- [x] I have read through the [contributing notes](https://github.com/plotly/plotly.py/blob/master/contributing.md) and understand the structure of the package. In particular, if my PR modifies code of `plotly.graph_objects`, my modifications concern the `codegen` files and not generated files.
- [ ] I have added tests (if submitting a new feature or correcting a bug) or
  modified existing tests.
- [ ] For a new feature, I have added documentation examples in an existing or
  new tutorial notebook (please see the doc checklist as well).
- [ ] I have added a CHANGELOG entry if fixing/changing/adding anything substantial.
- [ ] For a new feature or a change in behaviour, I have updated the relevant docstrings in the code to describe the feature or behaviour (please see the doc checklist as well).

### CODE REVIEW

**Comment by eisenlohr** [comment]
I am puzzled as to why the `build-doc` step is failing and why `test_optional/test_matplotlylib/test_bars.py` would now require reformatting (according to `black --check`).

  * The former appears to be a general problem across many of the recent PRs, so I assume that something more fundamental is amiss.
  * My own syntax check on `test_optional/test_matplotlylib/test_bars.py` did not result in errors and I would also not expect the simple substitutions made within the function calls to trigger a fresh syntax error.
Hence, this looks similar to the matter above being a general issue unrelated to the specific modifications done...

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg

**Comment by eisenlohr** [comment]
Hi Greg,

The changes that I was suggesting a couple of years ago might or might not be relevant in the current version. I have to admit that I did not follow this PR anymore.

Regarding general input into plotly, I would certainly be interested to voice an opinion primarily on the ECDF plot.

**Comment by gvwilson** [comment]
thanks @eisenlohr - I'm on the road next week, so could you please email me (greg.wilson@plot.ly) and we can find a time mid-July?

**Pull request closed without merging**
