### PR TITLE
Clarify Jupyterlab install

### PR DESCRIPTION
**Pull request by LiamConnors**
See https://github.com/plotly/plotly.py/issues/4581

### CODE REVIEW

**Review by Coding-with-Adam — APPROVED** [review]
This PR looks good to me, Liam. Thank you.

**Comment by gvwilson** [comment]
@marthacryan can you please give this a thumbs up?

**Review by marthacryan — APPROVED** [review]
LGTM!~

**Comment by gvwilson** [comment]
@marthacryan please go ahead and merge if you have the requisite magic powers

**Comment by marthacryan** [comment]
Not sure why, but the release_build CI failed, so I triggered a rerun in case it's just flaky. If not, I might need to look into why that would be showing up before I merge

**Pull request merged**
