### PR TITLE
Improve Periodic-table-example

### PR DESCRIPTION
**Pull request by janosh**
### Documentation PR

Improves the [custom-hovertext](https://plotly.com/python/annotated-heatmap/#custom-hovertext) annotated-heatmap example by hiding hover text on empty tiles and ensuring periodic table cells are squares.

- [x] I've [seen the `doc/README.md` file](https://github.com/plotly/plotly.py/blob/master/doc/README.md)
- [x] This change runs in the current version of Plotly on PyPI and targets the `doc-prod` branch OR it targets the `master` branch
- [x] Every new/modified example has a descriptive title and motivating sentence or paragraph
- [x] Every new/modified example is independently runnable
- [x] Every new/modified example is optimized for short line count	and focuses on the Plotly/visualization-related aspects of the example rather than the computation required to produce the data being visualized
- [x] Meaningful/relatable datasets are used for all new examples instead of randomly-generated data where possible
- [x] Large computations are avoided in the new/modified examples in favour of loading remote datasets that represent the output of such computations
- [x] Imports are `plotly.graph_objects as go` / `plotly.express as px` / `plotly.io as pio`
- [x] Data frames are always called `df`
- [x] `fig = <something>` call is high up in each new/modified example (either `px.<something>` or `make_subplots` or `go.Figure`)
- [ ] Liberal use is made of `fig.add_*` and `fig.update_*` rather than `go.Figure(data=..., layout=...)` in every new/modified example
- [ ] Specific adders and updaters like `fig.add_shape` and `fig.update_xaxes` are used instead of big `fig.update_layout` calls in every new/modified example
- [x] `fig.show()` is at the end of each new/modified example
- [x] `plotly.plot()` and `plotly.iplot()` are not used in any new/modified example
- [x] Hex codes for colors are not used in any new/modified example in favour of [these nice ones](https://github.com/plotly/plotly.py/issues/2192)

### CODE REVIEW

**Comment by janosh** [comment]
Now looks like this:
Screen Shot 2021-11-25 at 15 43 56

Before:
Screen Shot 2021-11-25 at 15 49 31

**Comment by nicolaskruchten** [comment]
Thanks! I've just merged some changes to this doc file so there are now some conflicts... Sorry!

**Comment by janosh** [comment]
All good now.

**Comment by nicolaskruchten** [comment]
Thanks!

**Pull request merged**
