### PR TITLE
Update _chart_types.py

### PR DESCRIPTION
**Pull request by yoonghm**
barnorm is default to None instead of ''

### CODE REVIEW

**Comment by yoonghm** [comment]
The default parameter barnorm in bar_polar() should be None, as stated in the document rather than the code. Please review.

**Comment by jonmmease** [comment]
Hi @yoonghm , thanks for your interest.  You're right that plotly.py does not explicitly include the default values of every property, and this is by design.  When a property is `None` on the Python side, this means that that the default will be chosen by the JavaScript library.

Is there a particular problem that you were trying to solve?

**Comment by nicolaskruchten** [comment]
This seems like a good modification, I can't think of a valid reason for it to be set to `""` in `bar_polar()` and `None` in `histogram()`.

**Comment by nicolaskruchten** [comment]
We should think about adding `barnorm` to `bar()` :)

**Pull request merged**
