### PR TITLE
Fixed show_edges and renamed dist_func to color_func

### PR DESCRIPTION
**Pull request by Kully**
@choldgraf

### CODE REVIEW

**Comment by choldgraf** [comment]
awesome - now we just need to wait on that lighting fix. I'll make a tiny
package to wrap some of the "activity" plots in high-level functions.

**Comment by Kully** [comment]
> awesome - now we just need to wait on that lighting fix. I'll make a tiny
> package to wrap some of the "activity" plots in high-level functions.

Okay. Shall I merge then?

**Comment by choldgraf** [comment]
I'm +1 on merge. I'll work with what's here a little bit and see if
anything comes up.

Chris

**Comment by choldgraf** [comment]
🍻

**Comment by choldgraf** [comment]
I'm getting some weird behavior now (working off the latest master). calling `iplot` now doesn't do anything...it looks to output something, but no plot is ever shown. It looks like something along these lines was changed recently...is anybody else experiencing this? @Kully @theengineear

**Comment by choldgraf** [comment]
weird, I tried it on another computer and now it works fine. maybe my browser crashed on the other one

**Comment by empet** [comment]
@choldgraf   There was/is a bug in plotly.js that stops displaying a plot when `plotly.offline.init_notebook_mode() ` is run twice. During the last week the  plotly.js  team  worked on this issue.
To check that your browser is working OK, just replace  the line of code
`plotly.offline.iplot(fig)` with `plotly.offline.plot(fig, filename='your-file.html)`.

**Pull request merged**
