### PR TITLE
Don’t hard-code repo name in circle-stuff.

### PR DESCRIPTION
**Pull request by theengineear**
Just uses the `$CIRCLE_PROJECT_REPONAME` environment variable that circle provides.

### CODE REVIEW

**Comment by theengineear** [comment]
I'm going to merge this when tests pass on this branch because it's holding up other builds. But, ping :)!

//cc @chriddyp

**Comment by chriddyp** [comment]
:dancer: thx man!

On Wed, Oct 14, 2015 at 1:02 AM, Andrew <notifications@github.com> wrote:

> Just uses the $CIRCLE_PROJECT_REPONAME environment variable that circle
> provides.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/plotly/plotly.py/pull/333
> Commit Summary
>
>    - Don’t hard-code repo name in circle-stuff.
>
> File Changes
>
>    - *M* circle.yml
>    <https://github.com/plotly/plotly.py/pull/333/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/plotly/plotly.py/pull/333.patch
>    - https://github.com/plotly/plotly.py/pull/333.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/plotly.py/pull/333>.
>



-- 
Chris Parmer
Plotly, Chief Product Officer
514 571 5897
https://plot.ly/team

**Comment by theengineear** [comment]
Hmmm hitting some pip-related snags:

* https://github.com/pypa/pip/issues/2903
* http://stackoverflow.com/questions/25036897/pip-install-unicodedecodeerror

These all seem to relate to unicode in the **path name** though, and i don't know where that would be occurring?

**Comment by theengineear** [comment]
hmmm here are the only non-unicode paths according to circle:

```
(venv-system)ubuntu@box227:/$ sudo LC_ALL=C find . -name '*[! -~]*' 2>&1 | grep -v "find"
./etc/ssl/certs/AC_Raíz_Certicámara_S.A..pem
./etc/ssl/certs/Certinomis_-_Autorité_Racine.pem
./etc/ssl/certs/NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem
./etc/ssl/certs/TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3.pem
./etc/ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı.pem
./usr/share/ca-certificates/mozilla/Certinomis_-_Autorité_Racine.crt
./usr/share/ca-certificates/mozilla/EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı.crt
./usr/share/ca-certificates/mozilla/TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3.crt
./usr/share/ca-certificates/mozilla/AC_Raíz_Certicámara_S.A..crt
./usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt
./home/ubuntu/.play/framework/test/integrationtest/app/controllers/πø$7ß.java
(venv-system)ubuntu@box227:/$ 
```

Note that you can't get permission to look in all the folders on circle, hence the `| grep -v "find"`, which excludes `find` errors.

**Comment by theengineear** [comment]
Also, pip is fully up to date, so there's nothing to be done there.

**Comment by theengineear** [comment]
I'm attempting to just install our deps manually with ssh to see if that fairs any better... pretty annoying non-support of unicode here though.

**Comment by theengineear** [comment]
I pinged the Circle team on this one to see if they might have some insight. I'll hop back on this tomorrow probably.

**Comment by theengineear** [comment]
Despite the pip error, the root cause (i think?) is that matplotlib 1.3.1 is just failing to install now.

**Comment by chriddyp** [comment]
@theengineear - did this get resolved? do you need some help? this is starting to block other PRs: https://github.com/plotly/plotly.py/pull/334

**Comment by theengineear** [comment]
@chriddyp I chatted with the circle guys about it a bit, it's just that matplotlib won't build.

How about I scrap the matplotlib-related tests for now? I'll just add an attribute and then ignore with `-a '!matplotlib'` or something? I don't know how long it will take to get that build back up and running, but it will probably take 1-2 hours of my time to just skip the matplotlib tests for now so we can keep moving forward.

**Comment by theengineear** [comment]
K, this checked out locally for me. I loaded up an environment without matplotlib installed and ran the tests.

This is definitely a band-aid, but it will get us passing again.

**Comment by theengineear** [comment]
Not going to investigate this right now, but we could also try bumping our Python 2.7.8 to 2.7.10, perhaps that's why it's not working?

**Comment by theengineear** [comment]
\o/ geez. back a float. sort of.

@chriddyp merging this in so we can move forward again!

**Comment by theengineear** [comment]
See #336 and #335

**Pull request merged**
