### PR TITLE
choropleth improvements

### PR DESCRIPTION
**Pull request by Kully**
addresses: https://github.com/plotly/plotly.py/issues/944

Also does:
- [x] enhancement from  https://github.com/plotly/plotly.py/issues/944
- [x] Turns off hover for the lines. It fights with hover for the centroids.
- [x] Turns on persistent selection api for the centroid points, so that the centroids are invisible until you select, then they show up in white with a thin border.
- [x] 0-pad the 4 digit FIPS numbers of the legend

### CODE REVIEW

**Comment by Kully** [comment]
@jackparmer ready for a review whenever tests are passing

**Comment by jackparmer** [comment]
💃 from me

**Comment by Kully** [comment]
@cldougl

**Comment by cldougl** [comment]
@Kully I don't think the package data should be added in the test directory: https://github.com/plotly/plotly.py/tree/master/plotly/tests/test_optional/test_figure_factory

don't you want to be testing that the package data is read properly from: https://github.com/plotly/plotly.py/tree/master/plotly/package_data ?

**Comment by cldougl** [comment]
re: https://github.com/plotly/plotly.py/pull/947#issuecomment-369282424
👍 yep version 2.5.0

**Comment by cldougl** [comment]
💃

**Pull request merged**
