### PR TITLE
update px colormodel parameter and pytest

### PR DESCRIPTION
**Pull request by liudj2008**
## Code PR

- [x] I have read through the [contributing notes](https://github.com/plotly/plotly.py/blob/master/contributing.md) and understand the structure of the package. In particular, if my PR modifies code of `plotly.graph_objects`, my modifications concern the `codegen` files and not generated files.
- [x] I have added tests (if submitting a new feature or correcting a bug) or
  modified existing tests.
- [x] For a new feature, I have added documentation examples in an existing or
  new tutorial notebook (please see the doc checklist as well).
**added parameter instructions in docstring of imshow function**
- [ ] I have added a CHANGELOG entry if fixing/changing/adding anything substantial.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Hello,

I'm sorry we've not had a chance to review this PR yet, but we might be able to do so this week if you still would like us to...

**Comment by liudj2008** [comment]
Thank you for your help! Let me know if you need anything else from me

**Comment by nicolaskruchten** [comment]
Ah well it looks like you force-pushed to `master` which reset this PR and closed it, so we'd need you to check out https://github.com/plotly/plotly.py/commit/7b99ee8ca2503012a4354349a5c2a9fa560815bd and create a branch on that commit and resubmit a PR from there if possible. If not we can try to cherry-pick those commits :)

**Comment by liudj2008** [comment]
I have recreated a new pull request  #2932
<https://github.com/plotly/plotly.py/pull/2932>. Looks like it has problems
in build-doc and python-2.7-optional. Thank you for helping me review the
request!

**Pull request closed without merging**
