### PR TITLE
Python 2/3 compat

### PR DESCRIPTION
**Pull request by scls19fr**
print as a function

### CODE REVIEW

**Comment by scls19fr** [comment]
https://plot.ly/pandas/getting-started/ should also be fixed

print plotly.__version__  # version >1.9.4 required

->

print(plotly.__version__)  # version >1.9.4 required

**Comment by chriddyp** [comment]
cc @cldougl for the docs ^^

**Comment by cldougl** [comment]
thanks @scls19fr ! I've updated the pandas getting started page as well.

**Comment by scls19fr** [comment]
I don't see anything related to Pandas now
https://plot.ly/pandas/getting-started/

Working with Blaze should also be considered
http://blaze.pydata.org/
(especially with Dash to avoid fetching all data to memory)

**Comment by cldougl** [comment]
Hi there,
The print statements on: https://plot.ly/pandas/getting-started/ have been updated, if you see any other issues on that page feel free to open an issue in our documentation repo: https://github.com/plotly/documentation

**Pull request merged**
