### PR TITLE
Add 'frames' to the ipython display_bundle

### LINKED ISSUE #737: Include `frames` in IPython display bundle (`application/vnd.plotly.v1+json`)
`frames` are not sent as JSON in display bundle. It needs to be added..

fyi .. @Kully , @scjody ..

### PR DESCRIPTION
**Pull request by tarzzz**
Fixes #737 ..

### CODE REVIEW

**Comment by tarzzz** [comment]
@cldougl : Please review.. (very minor change). This update will allow Plotly Cloud to render offline animations in notebooks.

We can also do a version bump for this one..

**Comment by cldougl** [comment]
@tarzzz can you comment here what additional steps need to be taken for offline animations to render in the cloud? Running the offline examples doesn't seem to work quite yet with these changes.

**Comment by tarzzz** [comment]
@cldougl It does not need any additional steps to work.

**Comment by cldougl** [comment]
(Related to backend pr)
💃🏻

**Pull request merged**
