### PR TITLE
go back to using git protocol

### PR DESCRIPTION
**Pull request by BRONSOLO**
looking to revert the protocol change. context: https://github.com/plotly/plotly.py/pull/325#issuecomment-147120176

ping @theengineear

### CODE REVIEW

**Comment by theengineear** [comment]
The url here [according to these docs](https://git-scm.com/docs/gitmodules) is passed directly to `clone`. Therefore, if the `git` is an issue, perhaps we should really go to the simplest form:

`https://github.com/chriddyp/chunked-requests`

??

**Comment by theengineear** [comment]
This can :dancer: or we can attempt to go to `https` as well.

**Comment by BRONSOLO** [comment]
Great. I think https should be fine. I say we revert to what we were using and if we ever have a problem with this, we should consider using https.

**Comment by theengineear** [comment]
^^ :+1: :dancer:

**Pull request merged**
