### PR TITLE
first pass at adding mathjax

### PR DESCRIPTION
**Pull request by chriddyp**
Using the workaround as suggested here:
https://github.com/plotly/plotly.py/issues/515#issuecomment-263097892

### CODE REVIEW

**Comment by chriddyp** [comment]
The codeblock as mentioned by @jjaraalm doesn't actually work for me. Perhaps that patch only works for a certain version of Jupyter?

image

The error from mathjax is pretty cryptic, I'm not very familar with how this works: https://github.com/mathjax/mathjax-docs/wiki/'Can't-make-callback-from-given-data'-error-if-resetEquationNumbers-is-called-when-no-math-is-typeset

**Comment by jjaraalm** [comment]
Wow. Completely forgot about this ... was going to make a PR at one time but just never did. I'll check this out tonight and see if I can help figure out what's going on.

**Comment by chriddyp** [comment]
@jjaraalm - that would be great, thank you!

**Comment by chriddyp** [comment]
Alternatively, sometimes I get this message
image

**Comment by jjaraalm** [comment]
I'm not having any issues on my end, so I'm going to just try and take a stab at what's going on for you. To me it looks like a configuration issue with the way Jupyter is setup or installed. In the first screenshot, you'll get that error if MathJax hasn't been started (by calling `MathJax.Hub.Configured()`), but both Jupyter and plotly.js should be calling that. For the second screenshot, it's failing to load the SVG config file `jax/output/SVG/config.js` for some reason. Can you check to make sure you have the file? If MathJax can't load the render config file, it looks like it just keeps trying and enters into an infinite loop.

Also, looks like you're running an older version of Jupyter. Current Jupyter ships with MathJax 2.6, but you have 2.5.3. Not sure if this is important though.

**Comment by jonmmease** [comment]
superseded by work in https://github.com/plotly/plotly.py/pull/1169

**Pull request closed without merging**
