### PR TITLE
dashboard box ids to letters

### PR DESCRIPTION
**Pull request by Kully**

### CODE REVIEW

**Comment by Kully** [comment]
Re: https://github.com/plotly/plotly.py/issues/757

**Comment by Kully** [comment]
@cldougl can you please review this guy before the documentation PR? I'm waiting for this to be merged so I can successfully run the new letter notation for inserting boxes (eg. `dboard.insert(box, 'above', 'd')`)

**Comment by cldougl** [comment]
not sure this change is worth backwards incompatibility. Imo it's sufficient to update the docs:


ie
```
box_a = {
    'type': 'box',
    'boxType': 'plot',
    'fileId': fileId_2,
    'title': 'box-for-dashboard',
    'shareKey': sharekey_from_url(url_2)
}
```
or
`my_dboard.insert(box_a, 'below', 2)`

**Comment by Kully** [comment]
Deciding to not follow throw -> backwards incompatibility not worth the change.

**Pull request closed without merging**
