### PR TITLE
Added documentation for create_gantt function

### PR DESCRIPTION
**Pull request by anuraghuram**
Please see suggested docstrings in lines 852-854.

### CODE REVIEW

**Comment by anuraghuram** [comment]
Question: I see in the original [issue](https://github.com/plotly/plotly.py/issues/1210) documentation is also required for  the```data``` (and ```description```) parameters. Can you please clarify how ```data```might differ from the ```df``` parameter?

**Comment by emmanuelle** [comment]
Hi @anuraghuram thank you for your PR! I think git treats this file as a completely new file because its path has changed, could you please move it (not git move it) to the existing path `packages/python/plotly/plotly/figure_factory/_gantt.py` and delete the file at the root of the repo in the index?

**Comment by anuraghuram** [comment]
> Hi @anuraghuram thank you for your PR! I think git treats this file as a completely new file because its path has changed, could you please move it (not git move it) to the existing path `packages/python/plotly/plotly/figure_factory/_gantt.py` and delete the file at the root of the repo in the index?

Hi @emmanuelle: new to github - can you please explain how to delete the file at the root?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Pull request closed without merging**
