### PR TITLE
fix #2279: add pandas as dependency of plotly[express] extra

### LINKED ISSUE #2279: Requires pandas, but not documented?
I'm new to plotly. I installed plotly with `pip install plotly==4.5.4` and when I tried to generate a graph, I got 'ImportError: Plotly express requires pandas to be installed.'

The getting-started page says "This package contains everything you need to write figures to standalone HTML files." I looked through the documentation, but couldn't find anywhere that said pandas was required, or how to install pandas.

To reproduce:
```
>>> import plotly.express as px
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ken/blog/corona/env/lib/python3.7/site-packages/plotly/express/__init__.py", line 12, in <module>
    Plotly express requires pandas to be installed."""
ImportError: Plotly express requires pandas to be installed.
```
Maybe this is intentional (see #2125), but I think the documentation should be clearer. Automatically installing pandas would be even better.

### PR DESCRIPTION
**Pull request by fokoid**
* This change allows package users to make the Pandas dependency of Plotly Express explicit by depending on/installing `plotly[express]`.
* The documentation part of the change is very minor and could have been done via the 'edit on Github' button so I didn't test the documentation build. However, I've left the checklist below for completeness.
* Does this merit a CHANGELOG entry?

### Documentation PR

- [X] I've [seen the `doc/README.md` file](https://github.com/plotly/plotly.py/blob/master/doc/README.md)
- [ ] This change runs in the current version of Plotly on PyPI and targets the `doc-prod` branch OR it targets the `master` branch
- [ ] If this PR modifies the first example in a page or adds a new one, it is a `px` example if at all possible
- [ ] Every new/modified example has a descriptive title and motivating sentence or paragraph
- [ ] Every new/modified example is independently runnable
- [ ] Every new/modified example is optimized for short line count	and focuses on the Plotly/visualization-related aspects of the example rather than the computation required to produce the data being visualized
- [ ] Meaningful/relatable datasets are used for all new examples instead of randomly-generated data where possible
- [ ] The random seed is set if using randomly-generated data in new/modified examples
- [ ] New/modified remote datasets are loaded from https://plotly.github.io/datasets and added to https://github.com/plotly/datasets
- [ ] Large computations are avoided in the new/modified examples in favour of loading remote datasets that represent the output of such computations
- [ ] Imports are `plotly.graph_objects as go` / `plotly.express as px` / `plotly.io as pio`
- [ ] Data frames are always called `df`
- [ ] `fig = <something>` call is high up in each new/modified example (either `px.<something>` or `make_subplots` or `go.Figure`)
- [ ] Liberal use is made of `fig.add_*` and `fig.update_*` rather than `go.Figure(data=..., layout=...)` in every new/modified example
- [ ] Specific adders and updaters like `fig.add_shape` and `fig.update_xaxes` are used instead of big `fig.update_layout` calls in every new/modified example
- [ ] `fig.show()` is at the end of each new/modified example
- [ ] `plotly.plot()` and `plotly.iplot()` are not used in any new/modified example
- [ ] Hex codes for colors are not used in any new/modified example in favour of [these nice ones](https://github.com/plotly/plotly.py/issues/2192)

## Code PR

- [X] I have read through the [contributing notes](https://github.com/plotly/plotly.py/blob/master/contributing.md) and understand the structure of the package. In particular, if my PR modifies code of `plotly.graph_objects`, my modifications concern the `codegen` files and not generated files.
- [ ] I have added tests (if submitting a new feature or correcting a bug) or
  modified existing tests.
- [X] For a new feature, I have added documentation examples in an existing or
  new tutorial notebook (please see the doc checklist as well).
- [ ] I have added a CHANGELOG entry if fixing/changing/adding anything substantial.
- [ ] For a new feature or a change in behaviour, I have updated the relevant docstrings in the code to describe the feature or behaviour (please see the doc checklist as well).

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks! What about `statsmodels` which is an optional dependency of Plotly Express (only for trendlines)? Should it be part of the `[express]` extra or do we need another extra like `[express-full]` or something?

**Comment by alexcjohnson** [comment]
Yes, I think if we do this we should have a single extra that includes `statsmodels` too. It's heavier for sure, especially since `statsmodels` brings in `scipy`, but IMO that's better than having two extras for two dependencies.

**Comment by emilykl** [comment]
@gvwilson This is a good change but it's out of date; we should put efforts towards #4644 which is more recent.

**Comment by gvwilson** [comment]
closed in favor of #4644

**Pull request closed without merging**
