### PR TITLE
Update percy tests to use maps

### PR DESCRIPTION
**Pull request by LiamConnors**

### CODE REVIEW

**Comment by archmoj** [comment]
Do we set unused plot config on any of these?

**Comment by LiamConnors** [comment]
> Do we set unused plot config on any of these?

I don't understand. Do you have an example of what this looks like?

**Comment by LiamConnors** [comment]
> > > Do we set unused plot config on any of these?
> > 
> > 
> > I don't understand. Do you have an example of what this looks like? And what's the impact of setting/not setting it for these tests?
> 
> I mean if you search inside these tests any of them using set mapbox token?

None of the tests are using that.

**Comment by archmoj** [comment]
Thanks. Wondering why some tests are failing?

**Review by gvwilson — APPROVED** [review]

**Pull request merged**
