### PR TITLE
Modify template generator to automatically add new `map` traces and subplots

### LINKED ISSUE #4879: Add `scattermap` and `map` to plotly.py templates similar to `scattermapbox` and `mapbox`
In order for `scattermap` and `map` behave similar to `scattermapbox` and `mapbox`, we should add `scattermap` and `map` to the templates inside `packages/python/plotly/plotly/package_data/templates/`.

### PR DESCRIPTION
**Pull request by archmoj**
Resolves #4879.

See #4879 for discussion.

1.  Move material from `packages/python/plotly/templategen/__init__.py` to new file `packages/python/plotly/templategen/__main__.py` so that we can run `python -m templategen` from the `packages/python/plotly` directory.
2.  Modify `packages/python/plotly/templategen/utils/__init__.py` to change `heatmapgl` reference to `heatmap`.
3.  Run `python -m templategen` to generate new versions of the following files:
    -   `packages/python/plotly/plotly/package_data/templates/ggplot2.json`
    -   `packages/python/plotly/plotly/package_data/templates/plotly.json`
    -   `packages/python/plotly/plotly/package_data/templates/plotly_dark.json`
    -   `packages/python/plotly/plotly/package_data/templates/plotly_white.json`
    -   `packages/python/plotly/plotly/package_data/templates/seaborn.json`
    -   `packages/python/plotly/plotly/package_data/templates/simple_white.json`

### CODE REVIEW

**Comment by gvwilson** [comment]
does this replace #4880 ?

**Comment by emilykl** [comment]
@archmoj @gvwilson Looks good.

Do we have any automated way of testing that these templates are working as expected?

**Comment by gvwilson** [comment]
The only way I can think of to test the templates themselves is to add something that parses the JSON and looks at the structure, but I don't think that would add much value, since it would basically be cloning the generator code.

**Review by alexcjohnson — APPROVED** [review]
💃

**Review by emilykl — APPROVED** [review]
🚀

**Pull request merged**
