### PR TITLE
Venturellac dev ff upset plot

### PR DESCRIPTION
**Pull request by venturellac**
## Code PR

- [ yes ] I have read through the [contributing notes](https://github.com/plotly/plotly.py/blob/master/contributing.md) and understand the structure of the package. In particular, if my PR modifies code of `plotly.graph_objects`, my modifications concern the `codegen` files and not generated files.
- [ yes, in figure_factory tests ] I have added tests (if submitting a new feature or correcting a bug) or
  modified existing tests.
- [there is a post on the forums: https://community.plotly.com/t/plotly-upset-plot/63858] For a new feature, I have added documentation examples in an existing or
  new tutorial notebook (please see the doc checklist as well).
- [ yes ] I have added a CHANGELOG entry if fixing/changing/adding anything substantial.
- [ not applicable I think since this is totally new] For a new feature or a change in behaviour, I have updated the relevant docstrings in the code to describe the feature or behaviour (please see the doc checklist as well).

-->

### CODE REVIEW

**Comment by Coding-with-Adam** [comment]
Thank you for the suggestion, @venturellac .
Currently, our focus is on Plotly Express, trying to expand its features. As such, our resources are limited when it comes to enhancing Figure Factory. 

One recommendation would be to create your own package, something called `plotly-upset` for example.

**Comment by soumilbaldota** [comment]
@venturellac Thank you so much for making this.

**Comment by alexcjohnson** [comment]
Thank you @venturellac - as mentioned above by @Coding-with-Adam, and described further in #4204, we will not be accepting new figure factories at this time. This is cool functionality though, and would be excellent as a separate package.

**Comment by maflot** [comment]
Is there any chance to reopen this in the future? @alexcjohnson

**Pull request closed without merging**
