### PR TITLE
Fix CI failure

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes the failing CI based on suggestions in [this comment](https://github.com/conda/conda-libmamba-solver/issues/283#issuecomment-1949560105).

### CODE REVIEW

**Comment by BRONSOLO** [comment]
I suggest @jonmmease and/or @LiamConnors should review : ) Removing my assignment (though code changes look OK to me in general)

**Review by archmoj — APPROVED** [review]
Thanks very much for the fix.
Looking good to me.
@LiamConnors Wondering this might be something we should also add to the release process?

:dancer:

**Comment by LiamConnors** [comment]
> Thanks very much for the fix. Looking good to me. @LiamConnors Wondering this might be something we should also add to the release process?
> 
> 💃

@archmoj which part of the release process might benefit from adding something based on this? I thought this PR fixes it

**Comment by archmoj** [comment]
> > Thanks very much for the fix. Looking good to me. @LiamConnors Wondering this might be something we should also add to the release process?
> > 💃
> 
> @archmoj which part of the release process might benefit from adding something based on this? I thought this PR fixes it

Just in case you noticed a similar bug during the release.

**Pull request merged**
