### PR TITLE
Template bis

### PR DESCRIPTION
**Pull request by emmanuelle**

### CODE REVIEW

**Comment by jonmmease** [comment]
Looks good to me.  The changes in the percy tests all look like improvements. And the chart studio test failure is unrelated so :dancer: from me.

**Comment by emmanuelle** [comment]
@jonmmease please bear with me I just pushed another commit with also pie automargin. Waiting for percy to run... If eveything is well I should be done

**Comment by jonmmease** [comment]
great. looks like the chart studio tests are passing now. Just a black formatting issue left

**Comment by nicolaskruchten** [comment]
This change moves the titles a bit closer to the tick labels by default, which I’m ok with. Maybe in some near future we can have the built in templates reduce the margins a bit too :)

**Comment by emmanuelle** [comment]
thanks Jon!

**Pull request merged**
