### PR TITLE
Sg scraper

### PR DESCRIPTION
**Pull request by emmanuelle**
This is an improvement of the sphinx-gallery scraper, which crawls only the directory of the example and now works for different structures of galleries (I was trying to add a plotly example to the gallery of scikit-image and it did not work with the scraper, with this change it is working).

A more sustainable mid-term change would be to add a `_repr_html_` method to the `BaseFigure` class (since the html would then be captured by sphinx-gallery) but for now the scraper works.

### CODE REVIEW

**Comment by emmanuelle** [comment]
oops I need to fix the tests!

**Comment by nicolaskruchten** [comment]
💃 when the tests pass, so long as this is confirmed to be a backwards-compatible change ... ?

**Comment by emmanuelle** [comment]
yes this is backward-compatible! Just a less convoluted (and more robust for some galleries) way of scraping png and html files.

**Comment by nicolaskruchten** [comment]
Oops forgot to ask for a change log item :)

**Pull request merged**
