### PR TITLE
Presentation setup.py fix

### PR DESCRIPTION
**Pull request by Kully**
is adding `presentation_objs` file to setup.

Do I need to update version number to 2.2.1?

cc @cldougl @chriddyp

### CODE REVIEW

**Comment by cldougl** [comment]
yep we'll have to bump the version number to resend to pip

**Comment by cldougl** [comment]
the fix looks good to me 👍  
@kully can you update the version & changelog in this pr?

**Comment by Kully** [comment]
> the fix looks good to me 👍
> @Kully can you update the version & changelog in this pr?

doing now

**Comment by cldougl** [comment]
💃  after tests pass

**Pull request merged**
