### PR TITLE
Ensure `plot` sends layout along.

### PR DESCRIPTION
**Pull request by theengineear**
I can’t believe that this wasn’t tested anywhere before!

### CODE REVIEW

**Comment by theengineear** [comment]
Whelp... this is why it's important to manually test things before you merge big changes 😊

**Comment by theengineear** [comment]
@Kully can you review please?

//cc @chriddyp bc i'm guess you'll be as surprised as i was!

**Comment by Kully** [comment]
> @Kully can you review please?

Will give it a review tomorrow.

**Comment by chriddyp** [comment]
🙇

**Comment by Kully** [comment]
@theengineear Looks good! 💃

**Pull request merged**
