### PR TITLE
adding repo and branch options to updateplotlyjsdev

### PR DESCRIPTION
**Pull request by zouhairm**
PR to address #2344 

## Code PR

- [x] I have read through the [contributing notes](https://github.com/plotly/plotly.py/blob/master/contributing.md) and understand the structure of the package. In particular, if my PR modifies code of `plotly.graph_objects`, my modifications concern the `codegen` files and not generated files.
- [ ] I have added tests (if submitting a new feature or correcting a bug) or
  modified existing tests.
- [x] For a new feature, I have added documentation examples in an existing or
  new tutorial notebook (please see the doc checklist as well).

### CODE REVIEW

**Comment by zouhairm** [comment]
looks like circle CI for 2.7 is failing (seems to be due to something unrelated to this PR though)
```
response = <Response [400]>

    def validate_response(response):
        """
        Raise a helpful PlotlyRequestError for failed requests.
    
        :param (requests.Response) response: A Response object from an api request.
        :raises: (PlotlyRequestError) If the request failed for any reason.
        :returns: (None)
    
        """
        if response.ok:
            return
    
        content = response.content
        status_code = response.status_code
        try:
            parsed_content = response.json()
        except ValueError:
            message = content if content else "No Content"
            raise exceptions.PlotlyRequestError(message, status_code, content)
    
        message = ""
        if isinstance(parsed_content, dict):
            errors = parsed_content.get("errors", [])
            messages = [error.get("message") for error in errors]
            message = "\n".join([msg for msg in messages if msg])
        if not message:
            message = content if content else "No Content"
    
>       raise exceptions.PlotlyRequestError(message, status_code, content)
E       PlotlyRequestError: Sorry, a file named 'is_share_key_included2_grid' already exists
```

**Comment by emmanuelle** [comment]
Thank you very much for your PR @zouhairm ! The CI failure is indeed unrelated to your PR has just been fixed in master. You can merge master and push to be sure that everything is ok.

**Comment by emmanuelle** [comment]
So this is really a cool pull request. I just used your branch to build with a development branch currently developed in plotly.js, this is going to be so useful. The only thing I want to check before merging is that the PR modifies the name of the plotlyjs version, even in the case of plotly/master. I wonder if we have things in the repo depending on this name. All tests pass which is a good baseline. @jonmmease is it ok for you modifying the plotlyjs version name? It's also easy to slightly modify the PR so that it is not changed in the case plotly/master.

**Comment by zouhairm** [comment]
Sounds good. Feel free to make the change or lmk and I can do it.

**Comment by nicolaskruchten** [comment]
This is a great change, thanks so much!

**Pull request merged**
