### PR TITLE
Update visualizing-mri-volume-slices.md

### PR DESCRIPTION
**Pull request by LeoMcBills**
I removed a trailing whitespace at the end of the file

### CODE REVIEW

**Comment by empet** [comment]
I think this example should be removed because the implementation is particular and can't be used for another image stack. This code was the first attempt to  animate slices, later generalized here: https://nbviewer.org/github/empet/Animating-MRI-scans/blob/master/scanning-the-head-classic.ipynb

**Comment by LiamConnors** [comment]
@empet and @gvwilson, yes that makes sense to me to just remove this page.

**Comment by gvwilson** [comment]
:+1: delete it please

**Comment by LiamConnors** [comment]
We've removed this page in another PR, so closing this one out.

**Comment by LeoMcBills** [comment]
Alright @LiamConnors, thank you.

**Pull request closed without merging**
