### PR TITLE
update offline to plotlyjs 1.9.0

### PR DESCRIPTION
**Pull request by cldougl**

### CODE REVIEW

**Comment by cldougl** [comment]
@chriddyp @theengineear  @yankev 
offline update to use plotly.js 1.9.0

**Comment by yankev** [comment]
Looks good.💃

**Comment by theengineear** [comment]
Thx :) lots of new stuff in there, eh? @cldougl feel like updating PyPI? I think the last time it was loaded there we were at 1.9.5.

**Comment by cldougl** [comment]
@theengineear 
already did :)

**Comment by theengineear** [comment]
@cldougl ah, sweet, the search in PyPI is just wonky then! Thanks!

**Pull request merged**
