### PR TITLE
Px bool

### LINKED ISSUE #2121: Coloring by boolean column type does not work
When trying to color a scatter plot by a `bool` column datatype, the colors do not show:

(see attached file for data)

```
grouped.dtypes

mean_ape            float64
measurement_type     object
note                 object
parameters           object
n_estimators          int64
max_depth             int64
bootstrap              bool
max_features        float64

fig = px.scatter(
    grouped,
    x="n_estimators",
    y="mean_ape",
    facet_row="measurement_type",
    color="bootstrap",
    title="Error vs Number of Estimators Colored by Bootstrap",
    height=1000, width=1600
)
```
Screen Shot 2019-06-17 at 08 52 13 EDT

However, if I convert the `bool` column to a `str`, then the colors correctly appear:

```
new_grouped = grouped.copy()
new_grouped['bootstrap'] = new_grouped['bootstrap'].astype(str)

fig = px.scatter(
    new_grouped,
    x="n_estimators",
    y="mean_ape",
    facet_row="measurement_type",
    color="bootstrap",
    title="Error vs Number of Estimators Colored by Bootstrap",
    height=1000, width=1600
)
```

Screen Shot 2019-06-17 at 08 53 13 EDT

[grouped.csv.zip](https://github.com/plotly/plotly_express/files/3297037/grouped.csv.zip)

### PR DESCRIPTION
**Pull request by emmanuelle**
Closes #2121

### CODE REVIEW

**Comment by emmanuelle** [comment]
Tests pass but one the other hand none of our datasets has a bool column I think...

**Comment by nicolaskruchten** [comment]
unfortunately this fails for `px.sunburst(path=[["yes", "no", "no"],["yes", "no", "a"]], color=[True, False, True])` for reasons that aren't super-clear to me at this point.

**Comment by nicolaskruchten** [comment]
interestingly, passing boolean color to sunburst works on master: it's treated as if it were 1s and 0s.

**Comment by emmanuelle** [comment]
The problem with sunburst has been fixed, this one should be ready for review.

**Comment by nicolaskruchten** [comment]
💃 when green!

**Comment by emmanuelle** [comment]
ok, do you want to greenify percy yourself to accept the new visuals?

**Pull request merged**
