### PR TITLE
first and last color of cyclicals should match

### PR DESCRIPTION
**Pull request by nicolaskruchten**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Without this fix:

image

With this fix:

image

**Comment by nicolaskruchten** [comment]
Note that the last two look markedly better, and the other ones that changed don't look all that different, because the last color didn't change all that much.

**Comment by emmanuelle** [comment]
Looks good ! Ideally we would document the new cyclical swatches function but maybe it should go instead to a new "colors" page of the documentation (I think you mentioned it previously). Maybe open an issue to remember that we need to document this? But this should not block the PR, so :dancer:

**Comment by nicolaskruchten** [comment]
I've just added this page in doc-prod https://plot.ly/python/builtin-colorscales/ so I'll update this PR to expand that page a bit :)

**Pull request merged**
