### PR TITLE
fixed skimage import

### LINKED ISSUE #1826: Does Plotly 4.2.0 depend on scikit-image?
I failed to `import plotly.figure_factory` because plotly seems not to install `scikit-image` when running `pip install -U plotly`. After I manually installed `scikit-image`, `import plotly.figure_factory` worked.

This was not a problem in version 4.1.1.

But the source code shows it depends on it.
https://github.com/plotly/plotly.py/blob/b7ad5433c4e0882715781fa6c4816fc7fff62965/packages/python/plotly/plotly/figure_factory/_ternary_contour.py#L11

### PR DESCRIPTION
**Pull request by emmanuelle**
Closes #1826 and #1829

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
So with this we just can’t see certain factories when the deps aren’t installed? Shouldn’t we just throw a call-time error instead? Otherwise someone will try to run the docs and be confused about import failures, no?

**Comment by nicolaskruchten** [comment]
Or does “optional imports” warn or something?

**Comment by emmanuelle** [comment]
We can probably import the dep inside the `ff` function instead, yes. I just copied the behaviour which was used for `pandas` and `county_choropleth`, I did not give it much thought

**Comment by nicolaskruchten** [comment]
💃

**Pull request merged**
