### PR TITLE
Add server_url to plotly.io.orca to allow for external orca server

### PR DESCRIPTION
**Pull request by miriad**
Add server_url to plotly.io.orca.config to allow an external orca server.

Implementation of #1570

### CODE REVIEW

**Comment by jonmmease** [comment]
Thanks @miriad! We'll try to take close look soon, and we should be able to get this in for version 4.3.0 (probably a week or two out).

**Comment by emmanuelle** [comment]
@miriad @jonmmease any idea of how to add tests for this? Open a local orca server and communicate with it?

**Comment by miriad** [comment]
@emmanuelle 

That's something I struggled with, because of the need to run an external service.

Seemingly, running a local orca server and communicating with it via localhost would be sufficient.

**Comment by jonmmease** [comment]
Looks great @miriad. I added a test, made a couple small cleanup changes, and merged master.   I'm very glad to have this option available now. Thanks!

**Comment by ferran-candela** [comment]
Hello,

I have tried to configure the external server by means of setting up the new available property 'server_url' but after doing it like this:

```
    import plotly.io as pio
    pio.orca.config.server_url = "localhost"
    pio.orca.config.port = 9091
```

The property 'executable' does not change to 'None' so the executable continues being required.

After debugging I have seen that the setter does not change the property since self._props is empty.
```
    @executable.setter
    def executable(self, val):

        if val is None:
            self._props.pop("executable", None)
```

Maybe I am not configuring it correctly.
Thanks.

**Comment by dev-dsp** [comment]
I can confirm that it just doesn't work. 
If I set executable to None by editing few lines in io/_orca.py, validate_executable() fails with exception, so it's not possible to run pio.to_image()

**Comment by miriad** [comment]
Please try including the port directly in server_url, such as "localhost:9091"

The port field is intended for use with a locally managed server, and setting will override the server_url field

**Comment by dev-dsp** [comment]
Please find my comment in above mentioned issue.

**Comment by dev-dsp** [comment]
Opened PR for fixing that: https://github.com/plotly/plotly.py/pull/1915

**Pull request merged**
