### PR TITLE
Require python 3.6 and CI maintenance

### PR DESCRIPTION
**Pull request by jonmmease**
This PR removes support for Python versions prior to 3.6 and does some clean up of the CI test suite.  In particular, it removes the use of tox and instead relies on a separate requirements.txt file for each Python version.  This makes it possible to test different versions of dependencies.

Still to do in follow-on PR(s)
 - Remove use of six for Python 2/3 compatibility
 - Unify optional requirements and doc requirements
 - Unify dependencies for conda+orca test job with optional requirements

Addresses parts of https://github.com/plotly/plotly.py/issues/3159 and closes https://github.com/plotly/plotly.py/issues/3158

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This PR looks fine to me, but I wonder if we shouldn't merge https://github.com/plotly/plotly.py/pull/2911 first and then bubble the `retrying`->`tenacity` changes through this PR prior to merge, to avoid making it harder to merge #2911

**Comment by jonmmease** [comment]
Yeah, that makes sense.  I'll go ahead and merge #2911 and update this PR.

**Comment by jonmmease** [comment]
ping @nicolaskruchten, I think this is ready to go now.  I added a few notes above for some follow ups that we can do next.

**Comment by nicolaskruchten** [comment]
💃

**Pull request merged**
