### PR TITLE
Plus 2 colorscale

### PR DESCRIPTION
**Pull request by Kully**
@theengineear  @jackparmer 

This pull request is for updating all my figurefactories (trisurf, scatterplotmatrix, violin, gantt eventually) so that they support more than 2 color lists as inputs.

I've only dealt with trisurf here, changing the framework for how colormap is validated.

Should I make separate branches for each of the figurefactories, or just work in this PR?

### CODE REVIEW

**Comment by theengineear** [comment]
>Should I make separate branches for each of the figurefactories, or just work in this PR?

Just doing it in *this* PR works for me.

**Comment by Kully** [comment]
@theengineear @jackparmer @choldgraf 

So Scatterplotmatrix has been completely reworked to allow for divergent and categorical colormaps. In particular, you can give it a list of an arbitrary number of colors (with mixing and matching color types) and it cat make a divergent colormap between these colors. 

If you want to assign specific index values to a specific color, just input colormap (new param) as a dictionary and assign a color to each value.

The tests should pass and some pictures are posted below.

I want to get this thing up and merged as soon as we can. Some of the trisurf code is old and has already been updated in master iirc.

scatterplot matrix - colormap dictionary

scatterplot matrix - intervals

**Comment by Kully** [comment]
divergent scale

**Comment by choldgraf** [comment]
yep, the trisurf code is already updated and there's a PR just needs some tiny fixes and will probably be ready to go today.

I am generally +1 to colormap improvements, as I've found it to be a little clunky. I basically just use helpers that take `matplotlib` colormaps and return `rgb` strings a ton (maybe that already exists in plotly though). There's also a big chunk of `create_trisurf` that is just choosing what colormap to use, and my guess is that could be wrapped up in a hidden function and applied to lots of other things in FF too.

**Comment by choldgraf** [comment]
Cool, lmk when you've had time to peek through mine and then it'll be ready
too

**Comment by Kully** [comment]
> Cool, lmk when you've had time to peek through mine and then it'll be ready
> too

Was about to check it out.

**Pull request merged**
