### PR TITLE
Improved compatibility with ipywidgtes and jupyter notebook

### PR DESCRIPTION
**Pull request by mtomassoli**
Please review & test this. I fixed it out of necessity but I only tested this on my own system.

This should solve issue #490.

### CODE REVIEW

**Comment by theengineear** [comment]
Thanks for the PR @mtomassoli, I'll do some manual testing ASAP.

**Comment by etpinard** [comment]
... with https://github.com/plotly/plotly.py/pull/549 now merged, we could now add a few test cases for widgets in NBs.

**Comment by rskabelund** [comment]
Hello, wondering if this ever made it into master?  Also, wondering about Jupyter 5.0 compatibility?

**Comment by Nahman78** [comment]
Hi, i tried this on my computer with ipython 5.1.0 and it's working. 
graphWidget.js is now on package_data/ so you need to apply small fix. I can provide a patch if you need to.
What is the next step to merge this into master ?
Thanks

**Comment by rskabelund** [comment]
@Nahman78 please elaborate on the small fix.  I have been having to do so many workarounds to use plotly in Jupyter that I think could have been address using the graphwidget...

**Comment by sfotiadis** [comment]
Hi, I've managed to apply the fix locally and works fine. https://github.com/sfotiadis/plotly.py/commit/c55f2a992684af1021ffe5df22f9617d964bf451 

Is there a plan to merge it?
Thanks

**Comment by Calebs97** [comment]
Any updates? I am still facing the same problem.

**Comment by Juanlu001** [comment]
Do the plotly developers have plan to include these updates, or perhaps are they working on an alternative approach? Not sure how #490 and #627 relate to #821 and https://github.com/jupyterlab/jupyter-renderers/issues/3. Any feedback would be appreciated, as I think there are a handful of people tracking those issues.

**Comment by jackparmer** [comment]
We're looking for some outside help for this and https://github.com/plotly/plotly.py/issues/821. No one at plotly has had time for the past year. Llamame at jack at plot dot ly if interested.

**Comment by jackparmer** [comment]
@Calebs97 merged your PR here https://github.com/plotly/plotly.py/commit/a226e07393c158e01c34c050aaf492da9d77679a`GraphWidget` is working OK for me on IPython v6.2.1, Python v3.6.3
image
Please let the thread know if you spot any issues.

**Comment by jonmmease** [comment]
Closing as `FigureWidget` has replaced the functionality of `GraphWidget` in version 3.

**Pull request closed without merging**
