### PR TITLE
use plotly.js-dist instead of plotly.js

### PR DESCRIPTION
**Pull request by archmoj**
Supersedes #3411
Addressing: https://github.com/plotly/plotly.js/issues/5966
cc: @FernandezMathieu

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This approach won't work... the overall code-gen system needs the full build. I can look into this next week or the week after.

**Comment by nicolaskruchten** [comment]
I'm curious about why you need to build the extension locally as opposed to downloading it from NPM or just letting the plotly.py installation process handle loading the extension?

**Comment by nicolaskruchten** [comment]
So Plotly.js 2.6 is now out and should be buildable again without needing to connect to Github... Could you please see if your issue is resolved?

**Comment by gvwilson** [comment]
@archmoj please let us know if this ought to be in Cycle 16

**Comment by archmoj** [comment]
It looks like plotly.py at the moment needs rebuild plot-schema.
So this require extra work.
Closing for now until but we may revisit this.

**Pull request closed without merging**
