### PR TITLE
add print_grid param to create_violin

### PR DESCRIPTION
**Pull request by Kully**

### CODE REVIEW

**Comment by Kully** [comment]
@cldougl @theengineear 
A response to this issue: https://github.com/plotly/plotly.py/issues/535. Do you guys think it _would_ be a good idea to provide this `print_grid` param for all FF's? This certainly solves the issue, but I think being consistent with this parameter would be a must afterwards. Thoughts?

**Comment by cldougl** [comment]
@Kully I think the violins were the only ones that used `make_subplots()` which was why the grid was printed.

**Comment by Kully** [comment]
> @Kully I think the violins were the only ones that used make_subplots() which was why the grid was printed.

Scatterplot Matrix does as well, iirc.

**Comment by Kully** [comment]
> Scatterplot Matrix does as well, iirc.

Shall I add the param to `.create_scatterplotmatrix` then?

**Comment by theengineear** [comment]
@Kully I'd suggest *not* exposing that to users. I can't see why there'd be much of a use-case for it. Just implicitly turn them off in the methods that use `make_subplots`. The FF methods are meant to be *helper* functions that reduce the cognitive load of constructing more complicated Plotly plots. Seem OK?

**Comment by Kully** [comment]
> @Kully I'd suggest not exposing that to users. I can't see why there'd be much of a use-case for it. Just implicitly turn them off in the methods that use make_subplots. The FF methods are meant to be helper functions that reduce the cognitive load of constructing more complicated Plotly plots. Seem OK?

Yes it does. I can make them implicit.

**Comment by Kully** [comment]
@theengineear Good to merge? I can make a PR for the Scatterplot Matrices FF and do the same thing...

**Comment by theengineear** [comment]
Yep, 💃!

**Pull request merged**
