### PR TITLE
[2.0.0] Unify API

### PR DESCRIPTION
**Pull request by theengineear**
I'm opening this up against a new `2.0.0` branch that we can work on and use as a merge base for all the things in https://github.com/plotly/plotly.py/issues/642

### CODE REVIEW

**Comment by theengineear** [comment]
@chriddyp @Kully, 💃? This is merging into the `2.0.0` branch, fyi. It won't get shipped until we get to everything we want to get to in https://github.com/plotly/plotly.py/issues/642.

**Comment by chriddyp** [comment]
💃

**Comment by chriddyp** [comment]
good stuff dude!

**Comment by Kully** [comment]
💃  from me too

**Pull request merged**
