### PR TITLE
Load graph reference from pkg copy of plot schema

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.py/issues/613

### CODE REVIEW

**Comment by etpinard** [comment]
### PROS

- `import plotly` will never break because of plot schema bugs e.g.https://github.com/plotly/plotly.js/pull/1182
- `import plotly` will never make a request to plot.ly 

### CONS

- `plotly.plotly` (i.e. users making graph via plot.ly) won't be relying in the _correct_ plot schema for key validation. For example, if we add an attribute to plotly.js and then to plot.ly, `plotly.plotly` users trying to user this attribute will get a validation error until we bump the [`default-schema.json`](https://github.com/plotly/plotly.py/blob/master/plotly/graph_reference/default-schema.json) during `plotly.offline` plotly.js version bumps.

I personally think the item under CONS isn't a big deal because:

- We should update the `plotly.offline` plotly.js frequently
- If a user _really_ want to use bleeding edge keys, they can always turn off validation

**Comment by etpinard** [comment]
cc @theengineear @chriddyp @cldougl @Kully

**Comment by theengineear** [comment]
@etpinard I'm shifting things around wrt our api for a large-ish release. I like the idea of no longer auto-downloading the plot-schema. We have a *very* simple way to update the plot schema and can just do that with minor version bumps if desired.

@chriddyp and @Kully, ya'll OK with stopping the auto-download of `plot-schema` as well?

**Comment by chriddyp** [comment]
I'm OK with it!

**Comment by theengineear** [comment]
The ideas from this have been implemented. Closing.

**Pull request closed without merging**
