### PR TITLE
fixed append_rows with string information

### PR DESCRIPTION
**Pull request by Kully**
Re: https://github.com/plotly/plotly.py/issues/774

### CODE REVIEW

**Comment by Kully** [comment]
@cldougl ready for 👀  after tests pass

**Comment by cldougl** [comment]
@Kully - nice! could you add a test for this?

**Comment by Kully** [comment]
> @Kully - nice! could you add a test for this?

You got it

**Comment by chriddyp** [comment]
has this issue been brought up with the @plotly/backend team? it sounds like it might be an issue with the grid API rather than our client implementation of it, but it's hard to say without seeing some handmade requests. Fixing it on the API side rather than the client-side is good because then everyone else who uses the API benefits from the fix

**Comment by cldougl** [comment]
@charleyferrari did you bring this up in backend by any chance?

**Comment by scjody** [comment]
This is the first I've heard of this issue. If you suspect a backend issue, please try and reproduce it with raw requests if possible and open an issue in the streambed repo.

**Comment by Kully** [comment]
Just wrote a test for this.

**Comment by Kully** [comment]
Closing as the issue no longer persists:
https://github.com/plotly/plotly.py/issues/774#issuecomment-313767993

**Pull request closed without merging**
