### PR TITLE
Unpin six in requirements.txt

### LINKED ISSUE #3301: Discrepancy between install_requires and requirements.txt
Question: Should we be pinning `six` at `1.15.0`? Now that `six` is on `1.16.0` this can lead to downgrades.

[From `setup.py`](https://github.com/plotly/plotly.py/blob/17b7c27f9e17b413b6958835ad53dc1aefb90834/packages/python/plotly/setup.py#L551):
```python
install_requires=["tenacity>=6.2.0", "six"],
```
There seems to be no pinning from `setuptools`.

However, [from `requirements.txt`](https://github.com/plotly/plotly.py/blob/17b7c27f9e17b413b6958835ad53dc1aefb90834/packages/python/plotly/requirements.txt#L9):
```python
six==1.15.0
```
(and also `tenacity>=6.2.0`)

I notice that six is slated for removal (#3167), so I hope the pinning is unnecessary, but I'm not sure.

Any guidance on this question would be very helpful over at conda-forge regarding https://github.com/conda-forge/plotly-feedstock/issues/94

### PR DESCRIPTION
**Pull request by maresb**
Closes #3301. See that for context.

(Regarding the checklist, this change is so trivial that I think most things are not applicable.)

## Code PR

- [X] I have read through the [contributing notes](https://github.com/plotly/plotly.py/blob/master/contributing.md) and understand the structure of the package. In particular, if my PR modifies code of `plotly.graph_objects`, my modifications concern the `codegen` files and not generated files.
- [ ] I have added tests (if submitting a new feature or correcting a bug) or
  modified existing tests.
- [ ] For a new feature, I have added documentation examples in an existing or
  new tutorial notebook (please see the doc checklist as well).
- [ ] I have added a CHANGELOG entry if fixing/changing/adding anything substantial.
- [ ] For a new feature or a change in behaviour, I have updated the relevant docstrings in the code to describe the feature or behaviour (please see the doc checklist as well).

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Yeah, makes sense :)

**Comment by nicolaskruchten** [comment]
Maybe this could just be >=1.15 instead?

**Comment by maresb** [comment]
@nicolaskruchten done.

**Comment by nicolaskruchten** [comment]
Thanks!

**Pull request merged**
